version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "php dependencies"
      - "backend"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "npm dependencies"
      - "frontend"
