name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: "testing"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Verify unittest DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'testing'"
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: |
          npm install
          npm run build
      - name: Run Code sniffer
        run: ./vendor/bin/phpcs    
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Database population
        run: |
          php artisan config:cache
          php artisan migrate
          php artisan db:seed
        env:
          DB_DATABASE: testing
      - name: Execute tests (Unit and Feature tests) via PHPUni
        run: ./vendor/bin/phpunit
